/**
 * The RailFlow network, copied verbatim from backend/data/railway_graph.json.
 *
 * Every station carries two positions: its real latitude/longitude and its
 * hand-drawn control-room diagram position (x, y). The page keeps both and
 * moves between them, exactly as the console does. Regenerate this file from
 * the backend data rather than editing it by hand.
 */

export const REGION = "Delhi Lucknow Operating Region";
export const SIM_START = "06:00";

export const STATIONS = [
  {"id": "NDLS", "name": "New Delhi", "lat": 28.6425, "lng": 77.2197, "x": 5, "y": 45, "type": "terminal", "dwell_base": 5},
  {"id": "DSA", "name": "Delhi Shahdara", "lat": 28.6733, "lng": 77.289, "x": 12, "y": 41, "type": "minor", "dwell_base": 2},
  {"id": "GZB", "name": "Ghaziabad Junction", "lat": 28.6692, "lng": 77.4538, "x": 20, "y": 42, "type": "junction", "dwell_base": 4},
  {"id": "PKW", "name": "Pilkhua", "lat": 28.7126, "lng": 77.6578, "x": 29, "y": 35, "type": "minor", "dwell_base": 2},
  {"id": "HPU", "name": "Hapur Junction", "lat": 28.7306, "lng": 77.7759, "x": 37, "y": 32, "type": "junction", "dwell_base": 3},
  {"id": "GMS", "name": "Garhmuktesar", "lat": 28.7873, "lng": 78.1011, "x": 47, "y": 28, "type": "minor", "dwell_base": 2},
  {"id": "GJL", "name": "Gajraula Junction", "lat": 28.8381, "lng": 78.2424, "x": 55, "y": 26, "type": "junction", "dwell_base": 3},
  {"id": "AMRO", "name": "Amroha", "lat": 28.9044, "lng": 78.4673, "x": 65, "y": 25, "type": "minor", "dwell_base": 2},
  {"id": "MB", "name": "Moradabad Junction", "lat": 28.8389, "lng": 78.7768, "x": 76, "y": 27, "type": "junction", "dwell_base": 5},
  {"id": "CH", "name": "Chandausi Junction", "lat": 28.4533, "lng": 78.7827, "x": 74, "y": 42, "type": "junction", "dwell_base": 3},
  {"id": "AO", "name": "Aonla", "lat": 28.2742, "lng": 79.1664, "x": 84, "y": 47, "type": "minor", "dwell_base": 2},
  {"id": "RMU", "name": "Rampur Junction", "lat": 28.7893, "lng": 79.0249, "x": 88, "y": 27, "type": "junction", "dwell_base": 3},
  {"id": "MIL", "name": "Milak", "lat": 28.6104, "lng": 79.1699, "x": 97, "y": 31, "type": "minor", "dwell_base": 2},
  {"id": "BE", "name": "Bareilly Junction", "lat": 28.3367, "lng": 79.4121, "x": 108, "y": 36, "type": "junction", "dwell_base": 5},
  {"id": "BEM", "name": "Budaun", "lat": 28.034, "lng": 79.1266, "x": 99, "y": 55, "type": "minor", "dwell_base": 2},
  {"id": "KSJ", "name": "Kasganj Junction", "lat": 27.8086, "lng": 78.6458, "x": 84, "y": 64, "type": "junction", "dwell_base": 3},
  {"id": "PMR", "name": "Pitambarpur", "lat": 28.1897, "lng": 79.6351, "x": 119, "y": 40, "type": "minor", "dwell_base": 2},
  {"id": "TLH", "name": "Tilhar", "lat": 27.9629, "lng": 79.7394, "x": 130, "y": 44, "type": "minor", "dwell_base": 2},
  {"id": "SPN", "name": "Shahjahanpur", "lat": 27.8833, "lng": 79.9122, "x": 141, "y": 46, "type": "junction", "dwell_base": 4},
  {"id": "AJI", "name": "Anjhi Shahabad", "lat": 27.6484, "lng": 79.9463, "x": 151, "y": 50, "type": "minor", "dwell_base": 2},
  {"id": "HRI", "name": "Hardoi", "lat": 27.3942, "lng": 80.1311, "x": 162, "y": 54, "type": "major", "dwell_base": 4},
  {"id": "SAN", "name": "Sandila", "lat": 27.0709, "lng": 80.514, "x": 174, "y": 61, "type": "minor", "dwell_base": 2},
  {"id": "AMG", "name": "Alamnagar", "lat": 26.8409, "lng": 80.8664, "x": 187, "y": 66, "type": "minor", "dwell_base": 2},
  {"id": "LKO", "name": "Lucknow Charbagh", "lat": 26.8315, "lng": 80.922, "x": 195, "y": 67, "type": "terminal", "dwell_base": 5},
  {"id": "KRJ", "name": "Khurja Junction", "lat": 28.2538, "lng": 77.8549, "x": 40, "y": 58, "type": "junction", "dwell_base": 3},
  {"id": "ALJN", "name": "Aligarh Junction", "lat": 27.8974, "lng": 78.088, "x": 55, "y": 69, "type": "junction", "dwell_base": 4},
  {"id": "HRS", "name": "Hathras Junction", "lat": 27.5999, "lng": 78.053, "x": 66, "y": 76, "type": "minor", "dwell_base": 2},
  {"id": "TDL", "name": "Tundla Junction", "lat": 27.2144, "lng": 78.2365, "x": 82, "y": 83, "type": "junction", "dwell_base": 4},
  {"id": "FZD", "name": "Firozabad", "lat": 27.1591, "lng": 78.3957, "x": 94, "y": 84, "type": "major", "dwell_base": 3},
  {"id": "SKB", "name": "Shikohabad Junction", "lat": 27.108, "lng": 78.5856, "x": 106, "y": 83, "type": "junction", "dwell_base": 3},
  {"id": "ETW", "name": "Etawah Junction", "lat": 26.7762, "lng": 79.0236, "x": 123, "y": 83, "type": "junction", "dwell_base": 4},
  {"id": "PHD", "name": "Phaphund", "lat": 26.5989, "lng": 79.4644, "x": 139, "y": 82, "type": "minor", "dwell_base": 2},
  {"id": "CNB", "name": "Kanpur Central", "lat": 26.4547, "lng": 80.3506, "x": 165, "y": 81, "type": "junction", "dwell_base": 5},
  {"id": "ON", "name": "Unnao Junction", "lat": 26.5471, "lng": 80.4894, "x": 179, "y": 76, "type": "junction", "dwell_base": 3},
  {"id": "FBD", "name": "Farrukhabad", "lat": 27.3905, "lng": 79.5816, "x": 135, "y": 66, "type": "junction", "dwell_base": 3},
  {"id": "KJN", "name": "Kannauj", "lat": 27.0552, "lng": 79.9181, "x": 151, "y": 70, "type": "major", "dwell_base": 3},
];

export const EDGES = [
  {"id": "NDLS-DSA", "from": "NDLS", "to": "DSA", "distance_km": 8, "avg_speed": 45, "capacity": 3},
  {"id": "DSA-GZB", "from": "DSA", "to": "GZB", "distance_km": 16, "avg_speed": 55, "capacity": 4},
  {"id": "GZB-PKW", "from": "GZB", "to": "PKW", "distance_km": 23, "avg_speed": 70, "capacity": 3},
  {"id": "PKW-HPU", "from": "PKW", "to": "HPU", "distance_km": 12, "avg_speed": 70, "capacity": 3},
  {"id": "HPU-GMS", "from": "HPU", "to": "GMS", "distance_km": 35, "avg_speed": 80, "capacity": 2},
  {"id": "GMS-GJL", "from": "GMS", "to": "GJL", "distance_km": 18, "avg_speed": 75, "capacity": 2},
  {"id": "GJL-AMRO", "from": "GJL", "to": "AMRO", "distance_km": 25, "avg_speed": 85, "capacity": 2},
  {"id": "AMRO-MB", "from": "AMRO", "to": "MB", "distance_km": 34, "avg_speed": 85, "capacity": 3},
  {"id": "MB-RMU", "from": "MB", "to": "RMU", "distance_km": 28, "avg_speed": 80, "capacity": 3},
  {"id": "RMU-MIL", "from": "RMU", "to": "MIL", "distance_km": 23, "avg_speed": 75, "capacity": 2},
  {"id": "MIL-BE", "from": "MIL", "to": "BE", "distance_km": 38, "avg_speed": 80, "capacity": 3},
  {"id": "BE-PMR", "from": "BE", "to": "PMR", "distance_km": 24, "avg_speed": 80, "capacity": 2},
  {"id": "PMR-TLH", "from": "PMR", "to": "TLH", "distance_km": 30, "avg_speed": 80, "capacity": 2},
  {"id": "TLH-SPN", "from": "TLH", "to": "SPN", "distance_km": 24, "avg_speed": 80, "capacity": 3},
  {"id": "SPN-AJI", "from": "SPN", "to": "AJI", "distance_km": 27, "avg_speed": 75, "capacity": 2},
  {"id": "AJI-HRI", "from": "AJI", "to": "HRI", "distance_km": 32, "avg_speed": 80, "capacity": 3},
  {"id": "HRI-SAN", "from": "HRI", "to": "SAN", "distance_km": 53, "avg_speed": 85, "capacity": 2},
  {"id": "SAN-AMG", "from": "SAN", "to": "AMG", "distance_km": 48, "avg_speed": 80, "capacity": 2},
  {"id": "AMG-LKO", "from": "AMG", "to": "LKO", "distance_km": 8, "avg_speed": 45, "capacity": 4},
  {"id": "GZB-KRJ", "from": "GZB", "to": "KRJ", "distance_km": 52, "avg_speed": 75, "capacity": 3},
  {"id": "HPU-KRJ", "from": "HPU", "to": "KRJ", "distance_km": 58, "avg_speed": 65, "capacity": 1},
  {"id": "KRJ-ALJN", "from": "KRJ", "to": "ALJN", "distance_km": 45, "avg_speed": 78, "capacity": 3},
  {"id": "ALJN-HRS", "from": "ALJN", "to": "HRS", "distance_km": 35, "avg_speed": 78, "capacity": 2},
  {"id": "HRS-TDL", "from": "HRS", "to": "TDL", "distance_km": 53, "avg_speed": 78, "capacity": 3},
  {"id": "TDL-FZD", "from": "TDL", "to": "FZD", "distance_km": 16, "avg_speed": 75, "capacity": 3},
  {"id": "FZD-SKB", "from": "FZD", "to": "SKB", "distance_km": 21, "avg_speed": 85, "capacity": 3},
  {"id": "SKB-ETW", "from": "SKB", "to": "ETW", "distance_km": 55, "avg_speed": 78, "capacity": 3},
  {"id": "ETW-PHD", "from": "ETW", "to": "PHD", "distance_km": 55, "avg_speed": 75, "capacity": 2},
  {"id": "PHD-CNB", "from": "PHD", "to": "CNB", "distance_km": 84, "avg_speed": 78, "capacity": 3},
  {"id": "CNB-ON", "from": "CNB", "to": "ON", "distance_km": 19, "avg_speed": 70, "capacity": 4},
  {"id": "ON-LKO", "from": "ON", "to": "LKO", "distance_km": 61, "avg_speed": 72, "capacity": 4},
  {"id": "MB-CH", "from": "MB", "to": "CH", "distance_km": 44, "avg_speed": 65, "capacity": 2},
  {"id": "CH-AO", "from": "CH", "to": "AO", "distance_km": 43, "avg_speed": 65, "capacity": 2},
  {"id": "AO-BE", "from": "AO", "to": "BE", "distance_km": 27, "avg_speed": 60, "capacity": 2},
  {"id": "ALJN-KSJ", "from": "ALJN", "to": "KSJ", "distance_km": 68, "avg_speed": 70, "capacity": 2},
  {"id": "KSJ-BEM", "from": "KSJ", "to": "BEM", "distance_km": 76, "avg_speed": 65, "capacity": 1},
  {"id": "BEM-BE", "from": "BEM", "to": "BE", "distance_km": 50, "avg_speed": 65, "capacity": 1},
  {"id": "SPN-FBD", "from": "SPN", "to": "FBD", "distance_km": 72, "avg_speed": 65, "capacity": 1},
  {"id": "FBD-KJN", "from": "FBD", "to": "KJN", "distance_km": 56, "avg_speed": 70, "capacity": 1},
  {"id": "KJN-CNB", "from": "KJN", "to": "CNB", "distance_km": 79, "avg_speed": 75, "capacity": 2},
  {"id": "HRI-KJN", "from": "HRI", "to": "KJN", "distance_km": 84, "avg_speed": 65, "capacity": 1},
  {"id": "HRI-ON", "from": "HRI", "to": "ON", "distance_km": 98, "avg_speed": 65, "capacity": 1},
];
